name: Render README

on:
  # Schedule updates (every 10 minutes)
  schedule: [{cron: "*/10 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}

jobs:
  render-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: diamondburned/nix-shell-action@9c50feff1c71026cc3aaf2b2d06aee1bca7a1047
        with:
          packages: curl, jq, bash, coreutils
          script: |
            ./update.sh
            echo "Updated README.md."
